// Generated by Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import AVFoundation;
@import ObjectiveC;
@import Foundation;
@import QuartzCore;
@import CoreGraphics;
@import CoreImage;
@import UIKit;
@import JavaScriptCore;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface AVPlayerLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface AVPlayerLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface AVPlayerLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface AVPlayerLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface AVPlayerLayer (SWIFT_EXTENSION(KiteKit))
@end


SWIFT_CLASS("_TtC7KiteKit6Action")
@interface Action : NSObject
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface Action (SWIFT_EXTENSION(KiteKit))
@end


@interface Action (SWIFT_EXTENSION(KiteKit))
@end


@interface Action (SWIFT_EXTENSION(KiteKit))
@end


@interface Action (SWIFT_EXTENSION(KiteKit))
@end


@interface Action (SWIFT_EXTENSION(KiteKit))
- (id _Nonnull)copy;
@end


@interface Action (SWIFT_EXTENSION(KiteKit))
@end


SWIFT_CLASS("_TtC7KiteKit15ActionEventType")
@interface ActionEventType : NSObject
- (id _Nonnull)copy;
- (BOOL)isEqual:(id _Nullable)object;
@property (nonatomic, readonly) NSUInteger hash;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7KiteKit18ActionResponseType")
@interface ActionResponseType : NSObject
- (id _Nonnull)copy;
- (BOOL)isEqual:(id _Nullable)object;
@property (nonatomic, readonly) NSUInteger hash;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7KiteKit14AsyncOperation")
@interface AsyncOperation : NSOperation
@property (nonatomic) BOOL isExecuting;
@property (nonatomic) BOOL isFinished;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface CAAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CAAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CAAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CAAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CAAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CAAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CAAnimationGroup (SWIFT_EXTENSION(KiteKit))
@end


@interface CAAnimationGroup (SWIFT_EXTENSION(KiteKit))
@end


@interface CAAnimationGroup (SWIFT_EXTENSION(KiteKit))
@end


@interface CAAnimationGroup (SWIFT_EXTENSION(KiteKit))
@end


@interface CAAnimationGroup (SWIFT_EXTENSION(KiteKit))
@end


@interface CABasicAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CABasicAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CABasicAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CAEmitterCell (SWIFT_EXTENSION(KiteKit))
@end


@interface CAEmitterCell (SWIFT_EXTENSION(KiteKit))
@end


@interface CAEmitterCell (SWIFT_EXTENSION(KiteKit))
- (id _Nonnull)copy;
@end


@interface CAEmitterCell (SWIFT_EXTENSION(KiteKit))
@end


@interface CAEmitterCell (SWIFT_EXTENSION(KiteKit))
@end


@interface CAEmitterCell (SWIFT_EXTENSION(KiteKit))
@end


@interface CAEmitterCell (SWIFT_EXTENSION(KiteKit))
@end


@interface CAEmitterLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAEmitterLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAEmitterLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAEmitterLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAEmitterLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAGradientLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAGradientLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAGradientLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAKeyframeAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CAKeyframeAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CAKeyframeAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit))
@end

@protocol CAAction;

@interface CALayer (SWIFT_EXTENSION(KiteKit))
- (id <CAAction> _Nullable)actionForLayer:(CALayer * _Nonnull)layer forKey:(NSString * _Nonnull)event;
@end


@interface CALayer (SWIFT_EXTENSION(KiteKit)) <CALayerDelegate>
- (void)drawLayer:(CALayer * _Nonnull)layer inContext:(CGContextRef _Nonnull)ctx;
@end


@interface CAMediaTimingFunction (SWIFT_EXTENSION(KiteKit))
@end


@interface CAMediaTimingFunction (SWIFT_EXTENSION(KiteKit))
@end


@interface CAMediaTimingFunction (SWIFT_EXTENSION(KiteKit))
@end


@interface CAPropertyAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CAPropertyAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CAReplicatorLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAReplicatorLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAReplicatorLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAScrollLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAScrollLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAScrollLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAShapeLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAShapeLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CAShapeLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CASpringAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CASpringAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CASpringAnimation (SWIFT_EXTENSION(KiteKit))
@end


@interface CATextLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CATextLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CATextLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CATextLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CATextLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CATiledLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CATiledLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CATiledLayer (SWIFT_EXTENSION(KiteKit))
@end


@interface CATransition (SWIFT_EXTENSION(KiteKit))
@end


@interface CAValueFunction (SWIFT_EXTENSION(KiteKit))
@end


@interface CAValueFunction (SWIFT_EXTENSION(KiteKit))
@end


@interface CIFilter (SWIFT_EXTENSION(KiteKit))
@end


@interface CIFilter (SWIFT_EXTENSION(KiteKit))
@end


SWIFT_CLASS("_TtC7KiteKit10CanvasInfo")
@interface CanvasInfo : NSObject
@property (nonatomic, readonly) CGSize canvasSize;
@property (nonatomic, readonly, strong) CALayer * _Nullable rootLayer;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (void)loadCanvasForQuickLook;
- (BOOL)loadCanvasAndReturnError:(NSError * _Nullable * _Nullable)error;
@end


SWIFT_CLASS("_TtC7KiteKit12DocumentInfo")
@interface DocumentInfo : NSObject
@property (nonatomic, readonly, copy) NSArray<CanvasInfo *> * _Nonnull canvasInfos;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC7KiteKit24DocumentPreviewOperation")
@interface DocumentPreviewOperation : AsyncOperation
- (void)start;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class NSCoder;

SWIFT_CLASS("_TtC7KiteKit24KiteBasePresentationView")
@interface KiteBasePresentationView : UIView
- (nonnull instancetype)initWithSize:(CGSize)size canvasInfo:(CanvasInfo * _Nonnull)canvasInfo OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass;
- (void)didMoveToWindow;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class KiteDocument;
@class NSBundle;

SWIFT_CLASS("_TtC7KiteKit34KiteBasePresentationViewController")
@interface KiteBasePresentationViewController : UIViewController
@property (nonatomic, readonly, strong) KiteDocument * _Nullable kiteDocument;
@property (nonatomic, readonly) BOOL isPresenting;
- (nullable instancetype)initWithFileURL:(NSURL * _Nonnull)fileURL;
- (nullable instancetype)initWithKiteDocument:(KiteDocument * _Nonnull)kiteDocument OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewDidAppear:(BOOL)animated;
- (BOOL)loadInitialCanvasAndReturnError:(NSError * _Nullable * _Nullable)error;
- (void)startPresenting;
- (void)stopPresenting;
- (void)pausePresentation;
- (void)resumePresentation;
- (void)rewind;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC7KiteKit12KiteDocument")
@interface KiteDocument : NSObject
@property (nonatomic, readonly, copy) NSURL * _Nullable fileURL;
@property (nonatomic, readonly, strong) DocumentInfo * _Nullable documentInfo;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (nonnull instancetype)initWithFileURL:(NSURL * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (BOOL)readForQuickLook;
- (BOOL)readAndReturnError:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface KiteDocument (SWIFT_EXTENSION(KiteKit))
@end

@class UIGestureRecognizer;
@class UITouch;
@class UIEvent;

SWIFT_CLASS("_TtC7KiteKit20KitePresentationView")
@interface KitePresentationView : KiteBasePresentationView
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
- (void)layoutSubviews;
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithSize:(CGSize)size canvasInfo:(CanvasInfo * _Nonnull)canvasInfo OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UIViewControllerTransitionCoordinator;

SWIFT_CLASS("_TtC7KiteKit30KitePresentationViewController")
@interface KitePresentationViewController : KiteBasePresentationViewController
@property (nonatomic) BOOL hidesStatusBar;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (nullable instancetype)initWithKiteDocument:(KiteDocument * _Nonnull)kiteDocument OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSAttributedString (SWIFT_EXTENSION(KiteKit))
@end


@interface NSNumber (SWIFT_EXTENSION(KiteKit))
@end


@interface NSObject (SWIFT_EXTENSION(KiteKit))
@end


@interface NSParagraphStyle (SWIFT_EXTENSION(KiteKit))
@end


@interface NSValue (SWIFT_EXTENSION(KiteKit))
@end


@interface NSValue (SWIFT_EXTENSION(KiteKit))
@end

@class JSValue;

SWIFT_CLASS("_TtC7KiteKit17NamedManagedValue")
@interface NamedManagedValue : JSManagedValue
- (nonnull instancetype)initWithValue:(JSValue * _Nonnull)value name:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
- (null_unspecified instancetype)initWithValue:(JSValue * _Null_unspecified)value SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC7KiteKit19PresentationContext")
@interface PresentationContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class JSContext;

@interface NSTimer (SWIFT_EXTENSION(KiteKit))
+ (void)prepareForPresentationInContext:(JSContext * _Nonnull)context;
@end


@interface UIBezierPath (SWIFT_EXTENSION(KiteKit))
@end


@interface UIBezierPath (SWIFT_EXTENSION(KiteKit))
@end


@interface UIColor (SWIFT_EXTENSION(KiteKit))
@end


@interface UIColor (SWIFT_EXTENSION(KiteKit))
@end


@interface UIColor (SWIFT_EXTENSION(KiteKit))
@end


@interface UIFont (SWIFT_EXTENSION(KiteKit))
@end


@interface UIFont (SWIFT_EXTENSION(KiteKit))
@end


@interface UIImage (SWIFT_EXTENSION(KiteKit))
@end


@interface UIImage (SWIFT_EXTENSION(KiteKit))
@end


@interface UIView (SWIFT_EXTENSION(KiteKit))
@end


@interface UIWindow (SWIFT_EXTENSION(KiteKit))
@end

#pragma clang diagnostic pop
